version: '3.9'
services:
  strapi:
    container_name: strapi-base
    image: lgdweb/strapi-base:latest
    restart: unless-stopped
    environment:
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      API_TOKEN_SALT: ${API_TOKEN_SALT}
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST:-strapi-base-DB}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: ${NODE_ENV}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database
      # - reverse-proxy-nw
    ports:
      - '1337:1337'
    depends_on:
      - strapi-base-DB

  strapi-base-DB:
    container_name: strapi-base-DB
    platform: linux/amd64
    restart: unless-stopped
    image: postgres:15.0-alpine
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - strapi-data:/var/lib/postgresql/data/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    networks:
      - database

volumes:
  strapi-data:
networks:
  database:
  # reverse-proxy-nw:
  #   external: true
